name: Build images

on:
  push:
  workflow_dispatch:

jobs:
  build-base:
    name: "GHCR: Build and push base"
    runs-on: ubuntu-latest
    environment:
      name: GHCR
      url: https://ghcr.io/its-me/workflow
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: ghcr.io/its-me/workflow:base

  build-successor:
    name: "GHCR: Build and push successor"
    needs: build-base
    runs-on: ubuntu-latest
    environment:
      name: GHCR
      url: https://ghcr.io/its-me/workflow
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile.successor
          push: true
          tags: ghcr.io/its-me/workflow:successor
